/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utility;

import graphs.*;
import java.awt.*;
import javax.swing.JColorChooser;

/**
 *
 * @author Administrator
 */
public class DragAndDrawAllInOne extends javax.swing.JFrame implements Runnable{

    Graphics g = null;
    Point p1, p2;
    Color color = Color.RED;
    Thread t;

    private PaintSurface shapes = new PaintSurface();

    public DragAndDrawAllInOne() {
        initComponents();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(shapes, BorderLayout.CENTER);
        buttonGroup1.add(rdDraw);
        buttonGroup1.add(rdFill);
        this.setSize(700, 500);
        this.rdFill.setEnabled(false);
        this.rdDraw.setSelected(true);
        this.txtBlack.setEditable(false);
        this.txtBlue.setEditable(false);
        this.txtGray.setEditable(false);
        this.txtGreen.setEditable(false);
        this.txtLavender.setEditable(false);
        this.txtOrange.setEditable(false);
        this.txtPink.setEditable(false);
        this.txtPurple.setEditable(false);
        this.txtRed.setEditable(false);
        this.txtYellow.setEditable(false);
        this.txtColor.setEditable(false);
        t = new Thread(this);
        t.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        pChooser = new javax.swing.JPanel();
        btnLine = new javax.swing.JButton();
        btnRectangle = new javax.swing.JButton();
        btnEllipse = new javax.swing.JButton();
        rdDraw = new javax.swing.JRadioButton();
        rdFill = new javax.swing.JRadioButton();
        btnColor = new javax.swing.JButton();
        txtBlack = new javax.swing.JTextField();
        txtGray = new javax.swing.JTextField();
        txtRed = new javax.swing.JTextField();
        txtYellow = new javax.swing.JTextField();
        txtOrange = new javax.swing.JTextField();
        txtGreen = new javax.swing.JTextField();
        txtPink = new javax.swing.JTextField();
        txtBlue = new javax.swing.JTextField();
        txtLavender = new javax.swing.JTextField();
        txtPurple = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lblCurrentColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLine.setText("Line");
        btnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineActionPerformed(evt);
            }
        });
        pChooser.add(btnLine);

        btnRectangle.setText("Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });
        pChooser.add(btnRectangle);

        btnEllipse.setText("Ellipse");
        btnEllipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllipseActionPerformed(evt);
            }
        });
        pChooser.add(btnEllipse);

        rdDraw.setText("Draw Only");
        rdDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDrawActionPerformed(evt);
            }
        });
        pChooser.add(rdDraw);

        rdFill.setText("Draw and Fill");
        rdFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFillActionPerformed(evt);
            }
        });
        pChooser.add(rdFill);

        btnColor.setText("Select Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        pChooser.add(btnColor);

        txtBlack.setBackground(new java.awt.Color(0, 0, 0));
        txtBlack.setFocusable(false);
        txtBlack.setOpaque(false);
        txtBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBlackMouseClicked(evt);
            }
        });

        txtGray.setBackground(new java.awt.Color(153, 153, 153));
        txtGray.setFocusable(false);
        txtGray.setOpaque(false);
        txtGray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGrayMouseClicked(evt);
            }
        });

        txtRed.setBackground(new java.awt.Color(255, 0, 0));
        txtRed.setFocusable(false);
        txtRed.setOpaque(false);
        txtRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRedMouseClicked(evt);
            }
        });

        txtYellow.setBackground(new java.awt.Color(255, 255, 0));
        txtYellow.setFocusable(false);
        txtYellow.setOpaque(false);
        txtYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtYellowMouseClicked(evt);
            }
        });

        txtOrange.setBackground(new java.awt.Color(255, 102, 0));
        txtOrange.setFocusable(false);
        txtOrange.setOpaque(false);
        txtOrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOrangeMouseClicked(evt);
            }
        });

        txtGreen.setBackground(new java.awt.Color(102, 255, 0));
        txtGreen.setFocusable(false);
        txtGreen.setOpaque(false);
        txtGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGreenMouseClicked(evt);
            }
        });

        txtPink.setBackground(new java.awt.Color(255, 102, 204));
        txtPink.setFocusable(false);
        txtPink.setOpaque(false);
        txtPink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPinkMouseClicked(evt);
            }
        });

        txtBlue.setBackground(new java.awt.Color(0, 0, 204));
        txtBlue.setFocusable(false);
        txtBlue.setOpaque(false);
        txtBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBlueMouseClicked(evt);
            }
        });

        txtLavender.setBackground(new java.awt.Color(204, 153, 255));
        txtLavender.setFocusable(false);
        txtLavender.setOpaque(false);
        txtLavender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLavenderMouseClicked(evt);
            }
        });

        txtPurple.setEditable(false);
        txtPurple.setBackground(new java.awt.Color(153, 0, 153));
        txtPurple.setFocusable(false);
        txtPurple.setOpaque(false);
        txtPurple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPurpleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblCurrentColor.setText("Current color: ");

        txtColor.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBlack)
                    .addComponent(txtGray)
                    .addComponent(txtRed)
                    .addComponent(txtYellow)
                    .addComponent(txtGreen)
                    .addComponent(txtOrange)
                    .addComponent(txtBlue)
                    .addComponent(txtPink)
                    .addComponent(txtPurple)
                    .addComponent(txtLavender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(lblCurrentColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(pChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(lblCurrentColor)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLavender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        color = JColorChooser.showDialog(this, "Choose a color", Color.BLACK);
        shapes.setColors(color);
    }//GEN-LAST:event_btnColorActionPerformed

    private void rdDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDrawActionPerformed
        shapes.setFill(false);
    }//GEN-LAST:event_rdDrawActionPerformed

    private void rdFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFillActionPerformed
        shapes.setFill(true);
    }//GEN-LAST:event_rdFillActionPerformed

    private void txtBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBlackMouseClicked
        shapes.setColors(Color.BLACK);
    }//GEN-LAST:event_txtBlackMouseClicked

    private void txtGrayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGrayMouseClicked
        shapes.setColors(Color.GRAY);
    }//GEN-LAST:event_txtGrayMouseClicked

    private void txtRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRedMouseClicked
        shapes.setColors(Color.RED);
    }//GEN-LAST:event_txtRedMouseClicked

    private void txtYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtYellowMouseClicked
        shapes.setColors(Color.YELLOW);
    }//GEN-LAST:event_txtYellowMouseClicked

    private void txtOrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrangeMouseClicked
        shapes.setColors(Color.ORANGE);
    }//GEN-LAST:event_txtOrangeMouseClicked

    private void txtGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGreenMouseClicked
        shapes.setColors(Color.GREEN);
    }//GEN-LAST:event_txtGreenMouseClicked

    private void txtPinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPinkMouseClicked
        shapes.setColors(Color.PINK);
    }//GEN-LAST:event_txtPinkMouseClicked

    private void txtBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBlueMouseClicked
        shapes.setColors(Color.BLUE);
    }//GEN-LAST:event_txtBlueMouseClicked

    private void txtLavenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLavenderMouseClicked
        shapes.setColors(new Color(204, 153, 255));
    }//GEN-LAST:event_txtLavenderMouseClicked

    private void txtPurpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPurpleMouseClicked
        shapes.setColors(new Color(153, 0, 153));
    }//GEN-LAST:event_txtPurpleMouseClicked

    private void btnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineActionPerformed
        this.rdFill.setEnabled(false);
        this.rdDraw.setSelected(true);
        shapes.setFill(false);
        shapes.setType(0);
    }//GEN-LAST:event_btnLineActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        this.rdFill.setEnabled(true);
        this.rdDraw.setSelected(true);
        shapes.setFill(false);
        shapes.setType(1);
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllipseActionPerformed
        this.rdFill.setEnabled(true);
        this.rdDraw.setSelected(true);
        shapes.setFill(false);
        shapes.setType(2);
    }//GEN-LAST:event_btnEllipseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        shapes.clearAll();
        this.jPanel1.updateUI();
    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    public void run() {
        while (true) {
            this.txtColor.setBackground(shapes.getColor());
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawAllInOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawAllInOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawAllInOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawAllInOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DragAndDrawAllInOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnEllipse;
    private javax.swing.JButton btnLine;
    private javax.swing.JButton btnRectangle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCurrentColor;
    private javax.swing.JPanel pChooser;
    private javax.swing.JRadioButton rdDraw;
    private javax.swing.JRadioButton rdFill;
    private javax.swing.JTextField txtBlack;
    private javax.swing.JTextField txtBlue;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtGray;
    private javax.swing.JTextField txtGreen;
    private javax.swing.JTextField txtLavender;
    private javax.swing.JTextField txtOrange;
    private javax.swing.JTextField txtPink;
    private javax.swing.JTextField txtPurple;
    private javax.swing.JTextField txtRed;
    private javax.swing.JTextField txtYellow;
    // End of variables declaration//GEN-END:variables
}
