/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphs;

import java.awt.*;
import javax.swing.JColorChooser;
import utility.*;

/**
 *
 * @author Administrator
 */
public class DragAndDrawTabbed extends javax.swing.JFrame implements Runnable {

    Graphics g = null;
    Point p1, p2;
    Color color = Color.RED;
    Thread t;

    private PaintSurface line = new PaintSurface(0);
    private PaintSurface rectangle = new PaintSurface(1);
    private PaintSurface ellipse = new PaintSurface(2);

    public DragAndDrawTabbed() {
        initComponents();
        this.jTabbedPane1.add("Line Shape", line);
        this.jTabbedPane1.add("Rectangle Shape", rectangle);
        this.jTabbedPane1.add("Eliipse Shape", ellipse);
        buttonGroup1.add(rdDraw);
        buttonGroup1.add(rdFill);
        rdDraw.setSelected(true);
        rdFill.setEnabled(false);
        this.setSize(700, 500);
        this.txtBlack.setEditable(false);
        this.txtBlue.setEditable(false);
        this.txtGray.setEditable(false);
        this.txtGreen.setEditable(false);
        this.txtLavender.setEditable(false);
        this.txtOrange.setEditable(false);
        this.txtPink.setEditable(false);
        this.txtPurple.setEditable(false);
        this.txtRed.setEditable(false);
        this.txtYellow.setEditable(false);
        this.txtColor.setEditable(false);
        t = new Thread(this);
        t.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pChooser = new javax.swing.JPanel();
        rdDraw = new javax.swing.JRadioButton();
        rdFill = new javax.swing.JRadioButton();
        btnColor = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        txtBlack = new javax.swing.JTextField();
        txtGray = new javax.swing.JTextField();
        txtRed = new javax.swing.JTextField();
        txtYellow = new javax.swing.JTextField();
        txtOrange = new javax.swing.JTextField();
        txtGreen = new javax.swing.JTextField();
        txtPink = new javax.swing.JTextField();
        txtBlue = new javax.swing.JTextField();
        txtLavender = new javax.swing.JTextField();
        txtPurple = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAllInOne = new javax.swing.JButton();
        lblCurrentColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdDraw.setText("Draw Only");
        rdDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDrawActionPerformed(evt);
            }
        });
        pChooser.add(rdDraw);

        rdFill.setText("Draw and Fill");
        rdFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFillActionPerformed(evt);
            }
        });
        pChooser.add(rdFill);

        btnColor.setText("Select Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        pChooser.add(btnColor);

        jTabbedPane1.setToolTipText("Lines");
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        txtBlack.setBackground(new java.awt.Color(0, 0, 0));
        txtBlack.setFocusable(false);
        txtBlack.setOpaque(false);
        txtBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBlackMouseClicked(evt);
            }
        });

        txtGray.setBackground(new java.awt.Color(153, 153, 153));
        txtGray.setFocusable(false);
        txtGray.setOpaque(false);
        txtGray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGrayMouseClicked(evt);
            }
        });

        txtRed.setBackground(new java.awt.Color(255, 0, 0));
        txtRed.setFocusable(false);
        txtRed.setOpaque(false);
        txtRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRedMouseClicked(evt);
            }
        });

        txtYellow.setBackground(new java.awt.Color(255, 255, 0));
        txtYellow.setFocusable(false);
        txtYellow.setOpaque(false);
        txtYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtYellowMouseClicked(evt);
            }
        });

        txtOrange.setBackground(new java.awt.Color(255, 102, 0));
        txtOrange.setFocusable(false);
        txtOrange.setOpaque(false);
        txtOrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOrangeMouseClicked(evt);
            }
        });

        txtGreen.setBackground(new java.awt.Color(102, 255, 0));
        txtGreen.setFocusable(false);
        txtGreen.setOpaque(false);
        txtGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGreenMouseClicked(evt);
            }
        });

        txtPink.setBackground(new java.awt.Color(255, 102, 204));
        txtPink.setFocusable(false);
        txtPink.setOpaque(false);
        txtPink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPinkMouseClicked(evt);
            }
        });

        txtBlue.setBackground(new java.awt.Color(0, 0, 204));
        txtBlue.setFocusable(false);
        txtBlue.setOpaque(false);
        txtBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBlueMouseClicked(evt);
            }
        });

        txtLavender.setBackground(new java.awt.Color(204, 153, 255));
        txtLavender.setFocusable(false);
        txtLavender.setOpaque(false);
        txtLavender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLavenderMouseClicked(evt);
            }
        });

        txtPurple.setEditable(false);
        txtPurple.setBackground(new java.awt.Color(153, 0, 153));
        txtPurple.setFocusable(false);
        txtPurple.setOpaque(false);
        txtPurple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPurpleMouseClicked(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAllInOne.setText("All in one drawing pane");
        btnAllInOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllInOneActionPerformed(evt);
            }
        });

        lblCurrentColor.setText("Current color: ");

        txtColor.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAllInOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblCurrentColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGray, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRed, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPink, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurple, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLavender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear)
                        .addComponent(btnAllInOne)
                        .addComponent(lblCurrentColor)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLavender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        color = JColorChooser.showDialog(this, "Choose a color", Color.BLACK);
        setSelectedColor(color);
    }//GEN-LAST:event_btnColorActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        int index = this.jTabbedPane1.getSelectedIndex();
        switch (index) {
            case 0:
                this.rdDraw.setSelected(true);
                this.rdFill.setEnabled(false);
                break;
            case 1:
                this.rdDraw.setSelected(true);
                this.rdFill.setEnabled(true);
                
                break;
            case 2:
                this.rdFill.setEnabled(true);
                break;
        }

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void rdDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDrawActionPerformed
        rectangle.setFill(false);
        ellipse.setFill(false);
    }//GEN-LAST:event_rdDrawActionPerformed

    private void rdFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFillActionPerformed
        rectangle.setFill(true);
        ellipse.setFill(true);
    }//GEN-LAST:event_rdFillActionPerformed

    private void txtBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBlackMouseClicked
        setSelectedColor(Color.BLACK);
    }//GEN-LAST:event_txtBlackMouseClicked

    private void txtGrayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGrayMouseClicked
        setSelectedColor(Color.GRAY);
    }//GEN-LAST:event_txtGrayMouseClicked

    private void txtRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRedMouseClicked
        setSelectedColor(Color.RED);
    }//GEN-LAST:event_txtRedMouseClicked

    private void txtYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtYellowMouseClicked
        setSelectedColor(Color.YELLOW);
    }//GEN-LAST:event_txtYellowMouseClicked

    private void txtOrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrangeMouseClicked
        setSelectedColor(Color.ORANGE);
    }//GEN-LAST:event_txtOrangeMouseClicked

    private void txtGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGreenMouseClicked
        setSelectedColor(Color.GREEN);
    }//GEN-LAST:event_txtGreenMouseClicked

    private void txtPinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPinkMouseClicked
        setSelectedColor(Color.PINK);
    }//GEN-LAST:event_txtPinkMouseClicked

    private void txtBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBlueMouseClicked
        setSelectedColor(Color.BLUE);
    }//GEN-LAST:event_txtBlueMouseClicked

    private void txtLavenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLavenderMouseClicked
        setSelectedColor(new Color(204, 153, 255));
    }//GEN-LAST:event_txtLavenderMouseClicked

    private void txtPurpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPurpleMouseClicked
        setSelectedColor(new Color(153, 0, 153));
    }//GEN-LAST:event_txtPurpleMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        int pos = this.jTabbedPane1.getSelectedIndex();
        if (pos == 0) {
            line.clearAll();
            line.updateUI();
        }
        if (pos == 1) {
            rectangle.clearAll();
            rectangle.updateUI();
        }
        if (pos == 2) {
            ellipse.clearAll();
            ellipse.updateUI();
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAllInOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllInOneActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DragAndDrawAllInOne().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAllInOneActionPerformed

    public void setSelectedColor(Color color) {
        int pos = this.jTabbedPane1.getSelectedIndex();
        if (pos == 0) {
            line.setColors(color);
        }
        if (pos == 1) {
            rectangle.setColors(color);
        }
        if (pos == 2) {
            ellipse.setColors(color);
        }
    }

    @Override
    public void run() {
        while (true) {
            int pos = this.jTabbedPane1.getSelectedIndex();
            if (pos == 0) {
                this.txtColor.setBackground(line.getColor());
            }
            if (pos == 1) {
                this.txtColor.setBackground(rectangle.getColor());
            }
            if (pos == 2) {
                this.txtColor.setBackground(ellipse.getColor());
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DragAndDrawTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DragAndDrawTabbed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllInOne;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnColor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCurrentColor;
    private javax.swing.JPanel pChooser;
    private javax.swing.JRadioButton rdDraw;
    private javax.swing.JRadioButton rdFill;
    private javax.swing.JTextField txtBlack;
    private javax.swing.JTextField txtBlue;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtGray;
    private javax.swing.JTextField txtGreen;
    private javax.swing.JTextField txtLavender;
    private javax.swing.JTextField txtOrange;
    private javax.swing.JTextField txtPink;
    private javax.swing.JTextField txtPurple;
    private javax.swing.JTextField txtRed;
    private javax.swing.JTextField txtYellow;
    // End of variables declaration//GEN-END:variables
}
